Improve error message when not enough arguments are given to a builder function.
Suppose you tried to create the following UpdateExpression:

    var b = require("ast-types").builders;

    b.updateExpression("++", b.memberExpression(
        b.identifier("a"), b.literal(0), true));

Before, it would fail with a cryptic message. Now, the problem is quickly discernible:

    AssertionError: no value or default function given for field "prefix" of
        UpdateExpression(operator: ++ | --, argument: Expression, prefix: boolean)

The updateExpression builder takes three arguments, and ours was missing the third.